on: push
name: Build Gatsby Site in Subdirectory
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Gatsby Site
      uses: oguzhankircali/oguzhankircali.github.io@master
      env:
        GATSBY_PROJECT_PATH: "./public"
      with:
        gatsby-arg: build